#!/bin/bash
#
# gen-cloudflare-realip.sh - Cloudflare の公開 IP レンジを取得し、
#   nginx(set_real_ip_from) / Apache(RemoteIPTrustedProxy) 用の行を生成する。
#
# 使い方:
#   scripts/gen-cloudflare-realip.sh --nginx                       # 標準出力に出す
#   scripts/gen-cloudflare-realip.sh --apache
#   scripts/gen-cloudflare-realip.sh --nginx -o /etc/nginx/conf.d/cloudflare-realip.conf --reload
#
# cron 例(毎月 1 日 4:10 に更新し、差分があれば reload):
#   10 4 1 * * /usr/local/bin/gen-cloudflare-realip.sh --nginx -o /etc/nginx/conf.d/cloudflare-realip.conf --reload
#
set -euo pipefail

MODE=""          # nginx | apache
OUT=""           # 出力先ファイル(未指定なら標準出力)
RELOAD=0         # 差分があれば reload するか

usage() {
  echo "usage: $0 (--nginx|--apache) [-o FILE] [--reload]" >&2
  exit 2
}

while [ $# -gt 0 ]; do
  case "$1" in
    --nginx)  MODE=nginx ;;
    --apache) MODE=apache ;;
    -o|--output) shift; OUT="${1:-}" ;;
    --reload) RELOAD=1 ;;
    -h|--help) usage ;;
    *) echo "unknown option: $1" >&2; usage ;;
  esac
  shift
done
[ -n "$MODE" ] || usage

V4_URL="https://www.cloudflare.com/ips-v4"
V6_URL="https://www.cloudflare.com/ips-v6"

# レンジを取得(IPv4 + IPv6)。取得失敗時は既存の出力を壊さないよう中断する。
ranges="$({ curl -fsS "$V4_URL"; echo; curl -fsS "$V6_URL"; } | sed '/^$/d')"
if [ -z "$ranges" ]; then
  echo "error: failed to fetch Cloudflare ranges" >&2
  exit 1
fi

case "$MODE" in
  nginx)  rendered="$(printf '%s\n' "$ranges" | sed 's/^/set_real_ip_from /; s/$/;/')" ;;
  apache) rendered="$(printf '%s\n' "$ranges" | sed 's/^/RemoteIPTrustedProxy /')" ;;
esac

header="# generated by gen-cloudflare-realip.sh on $(date +%F) - source: $V4_URL , $V6_URL"
content="$header"$'\n'"$rendered"

# 標準出力モード。
if [ -z "$OUT" ]; then
  printf '%s\n' "$content"
  exit 0
fi

# ファイル出力モード: 変化がなければ書き換えない(reload も走らせない)。
if [ -f "$OUT" ] && diff -q <(printf '%s\n' "$content") "$OUT" >/dev/null 2>&1; then
  echo "no change: $OUT"
  exit 0
fi

tmp="$(mktemp)"
printf '%s\n' "$content" > "$tmp"
install -m 644 "$tmp" "$OUT"
rm -f "$tmp"
echo "updated: $OUT"

if [ "$RELOAD" -eq 1 ]; then
  case "$MODE" in
    nginx)  nginx -t && systemctl reload nginx ;;
    apache) apachectl configtest && systemctl reload apache2 2>/dev/null || systemctl reload httpd ;;
  esac
fi
